storj-thirdparty/uplink-rust

uplink-sys/Cargo.toml
uplink-sys/build.rs

White list he typedef constants prefixed with UPLINK_ERROR_ in the
uplink-c in Bindgen so they are processed to be available in Rust.

uplink-sys: Allow typedef ERROR constants in Bindgen

---

uplink/Cargo.toml
uplink/README.md

Add an initial README for the `uplink` crate because it was missed on
the crate initialization commit.
Bump the crate version for being able to update the already published
crate for showing this README.

uplink(doc): Add initial README

---

uplink-sys/Cargo.toml

Fix the `links` Cargo key, bump the Rust edition and remove a comment
which is added when a Cargo project is initialized.
I've diffted the build output and there isn't any result difference.

uplink-sys(build): Fix key in cargo & bump edition

---

uplink-sys/Cargo.toml

Bump the Bindgen version to the last published release.
__NOTE__ it's on top of #5  so review and merge that one before this one.

uplink-sys(build): Bump bindgen version

---

uplink-sys/Cargo.toml
uplink/README.md

Bump the version of the Uplink C bindings to the last published release
which is v1.5.0.
Add some metadata to Cargo regarding Uplink C bindings and bump the
crate version.
Add the new entities to implement in `uplink` crate because of the new
additions that the new Uplink-C has and also some new integration test
to implement regarding to them.

uplink-sys(deps): Bump uplink-c version to v1.5.0

---

uplink-sys/Cargo.toml

In a previous commit the version for Uplink-c was bumped and the version
of the `uplink-sys` crate too, however, the `uplink-sys` version wasn't
properly increased although it wouldn't break anything.
This commit set the proper version taking advantage that so far the new
version has not been published yet in crates.io.

uplink-sys(cargo): Fix version before publishing it

---

uplink-sys/Cargo.toml
uplink-sys/Makefile
uplink-sys/build.rs
uplink-sys/tests/list_buckets.rs

Bump the uplink-c version to 1.6.1 (the last published version so far).
Arrange the build script for making it work with Go 1.18 but keeping
compatibility with the previous supported Go versions.
Enhance the test to read the passphrase from the secrets file rather
than requiring to be empty because the satellite web UI doesn't
currently allow setting an empty passphrase.
Closes #9
Once it's approved and merged, I will create the tag and publish the new crate version on crates.io

uplink-sys(deps): Bump uplink-c version to v1.6.1

---

uplink-sys/Cargo.toml

Bump the uplink-c version to 1.7.0 (the last published so far).
We have bumped to this new minor version without updating to the next
patch version because the next patch version only had changes in the
dependencies, nothing from the API was changed, removed, or added.
Related to #15

uplink-sys(deps): Bump uplink-c version to v1.7.0

---

.github/workflows/uplink-sys.yml
.github/workflows/uplink.yml
Makefile
uplink-sys/Makefile

Generalize the repository having a Makefile in the root directory to run
the same target to all the crates that it contains.
Change the uplink workflow for using the root Makefile for building the
uplink-sys crate rather than executing the direct Makefile target of the
uplink-sys crate.
Remove unnecessary verbose comments in the uplink-sys Makefile and
Github workflow and apply some other changes to homogenize them with the
uplink ones.

all(ci): Generalize & homogenize GH Actions workflows

---

uplink/src/access.rs
uplink/src/encryption_key.rs
uplink/src/object/upload.rs

Rust linter shows some warning about functions, methods, and members
visibility.
Not always those warnings apply because it doesn't consider that some
members are read if they are passed to the FFI as raw pointers, however,
it was right for these ones. These ones must be public otherwise the
dependents of this crate cannot use them.
The commit also remove an explicit borrow because the compiler is
already doing it automatically. This was reported as an error by a newer
version of Clippy running on local.

uplink(fix): Make a ctor & member public

---

uplink-sys/Cargo.toml
uplink/Cargo.toml

Bump the version to all the crates in this repository.
This new `uplink-sys` version includes a workaround for making possible
to build the documentation of the `uplink-sys` by docs.rs, and
consequently, for any crate that depends on it.
The new `uplink` version exposes with public visibility some existing
functions and fields that weren't exposed initially by mistake and
address a Clippy error. It also updates the `uplink-sys` dependency to
the version that this commit bumps.
---
Once it's merged, I'll create the new tags and publish the version of each crate.

all(release): Bump version to all crates

---

README.md
uplink-sys/README.md
uplink/README.md

Add badges to all the READMES.
The badges are:
* Github actions status.
* Crates.io latest published version.
* Docs.rs link to the docs of the latest version.
* Crates.io downloads
The main README reference to the `uplink` crate because it's the
idiomatic and safe implementation, hence everybody should use that one.
The README of each specific crate links to its own Github action,
Crates.io, and Docs.io.
Before this only the `uplink-sys` README had Github actions badges and
crates.io.
This commit also changes the style of the badge and mark as done one fo
the tasks listed in the `uplink` README which was missed when it was
completed.
Closes #25

all(doc): Add missing badges to READMEs

---

uplink-sys/README.md
uplink-sys/src/lib.rs

Remove some old TODO comments that indicated to update once `uplink-sys`
crate is published in crates.io and once a safe and idiomatic wrapper
crate exists. Both things are now a reality and these TODOs weren't
deleted at the time that those happen.
Moreover format README headers for following suggested Markdown
conventions.

uplink-sys(docs): Delete old TODOs & format README

---

uplink/src/object.rs
uplink/tests/full_cycle_test.rs

The Uplink-c library may return 0 bytes read when downloading an object,
despite not all the data being read. This usually happens when the object
has more than one segment and the read happens between the segments'
boundaries
Without retrying the crate won't allow downloading the entire object's
data when it has more than one segment.
On the other hand, a reader
(https://doc.rust-lang.org/std/io/trait.Read.html) implementation offers
a great number of useful methods out of the box with only implementing
the `read` method, however, read has only to return 0 bytes read when
there is no more data to read, rather than returning EOF as an error.
This commit identifies when Uplink-c returns the EOF error and returns
no error with the bytes read, that in case of not being 0, Rust will
call it …

uplink(fix): Retry on length 0 when downloading

---

uplink/Makefile

We relied on storj-up latest commit in the main branch however new
recent commits have broken it.
To not break it in our local and CI environments, we are compiling
storj-up in a commit that worked when we started to use it here at the
expense that we'll have to update from time to time.
On the other hand, we have requested to start using tag versions in the
storj-up repository because of this.
There is also another commit to remove an empty makefile target that was left
when working on #28

Fix storj-up after latest is broken

---

uplink/Cargo.toml

Bump the version of the uplink crate after a few commits that have fixed
some bugs and make the crate usable.
We know that those fixes made it usable because we had our first
integration test that it does a basic full-cycle and without them the
test wouldn't have passed.
I forgot to add this commit in the PR #28 I need this for releasing the new version

uplink(release): Bump version due to several fixes

---

uplink/Makefile
uplink/tests/docker-compose.yaml

storj-up has the first published release v1.0.0. Before we were using the `main` branch to compile the tool until some commits landed in `main` broke the integrations tests because a storj-up functionality stopped to work, hence, we had to hard code a commit hash to compile it.
Now storj-up repository has the first release and tag and it will publish them from time to time, we can use them rather than hard coding Git commit hashes.
This commit updates the Makefile to use v1.0.0 tag and updates the docker-compose file that storj-up generates because the new version bring changes.
closes #33

uplink(maintenance): Bump storj-up tool to v1

---

uplink/tests/access_grant_test.rs
uplink/tests/full_cycle_test.rs

Reorganize the imports groups in the integration tests to be consistent with the organization used in the implementation.
The used organization groups across the crate should be
* Modules defined in this crate.
* Standard library imports.
* External dependencies crates.

uplink(refactor): Reorganize imports in tests

---

uplink/Cargo.toml
uplink/README.md
uplink/src/object/upload.rs
uplink/tests/uploads_test.rs

This commit has several integration tests about object uploads and related methods.
When writing these tests, I found a bug due to a bad design. See the commit message for more information.
Unfortunately, the changes for solving the bug are breaking changes, so once this commit is approved, __DO NOT MERGE IT__ because I will publish a new minor version (v0.5.0) of the uplink crate before merging to the `main` branch and create the corresponding tag.

Uplink: Uploads integration tests

---

uplink/README.md
uplink/tests/object_test.rs

Implement the integration tests for object operations that weren't
tested in other tests.
~~This PR depends on the changes on #39 .~~
~~Review first #39, this PR is only 1 commit and it will be rebased once #39 is merged.~~

Uplink: Object integration tests

---

uplink-sys/build.rs

Remove needless references of types/values that are already referenced.
This issue was reported by Clippy linter after it was updated.
See https://github.com/storj-thirdparty/uplink-rust/actions/runs/3549876475/jobs/5962723049#step:4:64

uplink-sys(fix): Remove needless borrow

---

uplink/README.md
uplink/src/docs.rs
uplink/src/docs/design.rs
uplink/src/docs/storj.rs
uplink/src/edge/linksharing.rs
uplink/src/error.rs
uplink/src/object.rs

- Add a documentation page about Storj network in general (mimics https://pkg.go.dev/storj.io/uplink#section-documentation)
- Rename the architecture documentation page to design.
- Some minor documentation fixes and improvements.
See and read each commit individually to find more details.

Uplink: Add general docs & minor docs improvements/fixes

---

uplink/Cargo.toml
uplink/README.md
uplink/src/edge/config.rs
uplink/tests/edge_test.rs

This PR adds add some integration tests for the Edge service API.
There is a method that I don't think can be tested with `storj/up`, but I asked on   https://github.com/storj/up/issues/59 . If it's, I will finish it and enable it in a subsequent PR.
When I was implementing these tests, I found a fault in the API design and I addressed it in this PR (see commit messages) as a fix, however, they are breaking changes.
~This PR doesn't include any version release, despite the mentioned fix, because I'm going to add some general documentation soon and send a new PR with them,  and I will create a release with the changes in this PR and the one that I will push soon.~
This PR includes a commit for releasing a new version, but it already comments that it includes some documentation changes that …

Uplink: Add integration test for Edge services API

---

uplink/Makefile
uplink/tests/docker-compose.yaml

Bump the storj-up version for using the last published release.
Closes #47

uplink(chore): Bump storj-up version

---

README.md
uplink-sys/README.md
uplink/README.md

Update the "build" badge in all the READMEs because they changed the URL.
See: https://github.com/badges/shields/issues/8671

all(doc): Fix build badge in all READMEs

---

uplink/Makefile
uplink/README.md
uplink/src/error.rs
uplink/src/object.rs
uplink/src/project.rs
uplink/tests/edge_test.rs
uplink/tests/uploads_test.rs

All the planned end-to-end tests were finished in version v0.6.0 but the
README wasn't tidied according to them.
This commit tidies the README and also identifies all the `TODO`
comments with an issue for tracking them in the issue tracker for having
a good overview of what has to be done.
NOTE I created all the issues referred to by the `TODO` comments.

uplink(doc): Tidy README and TODO comments

---

.github/workflows/uplink-sys.yml
.github/workflows/uplink.yml
Makefile

The currently used version of storj-up (v1.0.0) doesn't compile with Go 1.20 because it relies on a version of Go QUIC as a transient dependency that doesn't compile with this Go version.
A current workaround is to disable QUIC for building storj-up until we bump storj-up to a newer published version that works with Go 1.20 without disabling QUIC.
In order to run the CI I had to modify the workflows, so there is a commit that just does that and it has its proper commit message.
Please see the commits message individually for more details and if you __MERGE THIS__ keep the commits, __DO NOT SQUASH__ them.

Compile storj-up without QUIC

---

uplink-sys/Makefile
uplink/Makefile

NixOS doesn't have `#!/bin/bash`. Bash can be found on all Linuxes with
`#!/usr/bin/env bash` so it's better to use that shebang. 
This doesn't actually enable building on NixOS since `uplink-c` also
needs upgrading to a version that doesn't use `#!/bin/bash`. This was done in
https://github.com/storj/uplink-c/pull/24
related https://github.com/storj-thirdparty/uplink-rust/issues/49

all(build): Change shebang for better compatibility

---

uplink-sys/.docs-rs/libuplink.pc
uplink-sys/.docs-rs/uplink/uplink.h
uplink-sys/.docs-rs/uplink/uplink_definitions.h
uplink-sys/Cargo.toml
uplink-sys/Makefile
uplink-sys/tests/list_buckets.rs
uplink/Cargo.toml
uplink/src/edge/config.rs
uplink/src/encryption_key.rs
uplink/src/error.rs
uplink/src/metadata.rs
uplink/src/object.rs
uplink/src/object/upload.rs
uplink/src/project/options.rs
uplink/tests/access_grant_test.rs
uplink/tests/edge_test.rs
uplink/tests/object_test.rs

This PR bumps the uplink-c for the uplink-sys crate and after the uplink-sys for the uplink crate to the last published versions and makes the necessary adjustments with the new version and functionalities.
There are also some minimal changes not related to the goal of the PR, but they are in different commits with their own proper description.
Uplink-sys is already published in crates.io, otherwise, the CI doesn't pass.
After this gets merged, I'll tag the repository with the version of the uplink and publish the new version in crates.io.
Closes #49

uplink / uplink-sys: Update uplink and uplink-sys to the latest version uplink-c

---

uplink/Cargo.toml

Bump the crate version to release the last fix.
The new crate release has already been published.

uplink(chore): Bump crate version

---

uplink/Cargo.toml

Bump the uplink-sys version crate to v0.6.1 (patch) and bump the uplink crate to a new patch release.
We can do this bump because we closed #71  and released the new version in crates.io.
Once, it's approved, I will publish the new version of the uplink crate.

uplink(desp): Bump uplink-sys verstion to v0.6.1

---

uplink-sys/build.rs

We bumped bindgen, but we didn't realize that the new version deprecated an API type that we were using.
This commit change the deprecated API type by the call to a constructor that replaces it, see
https://docs.rs/bindgen/0.69.4/bindgen/constant.CargoCallbacks.html

uplink-sys(build): Fix bindgen deprecation

---

uplink-sys/build.rs

This fixes an issue where:
1. User tries to build before initializing all submodules.
2. `uplink-c` directory is empty and copied into build.
3. Build fails but leaves empty `uplink-c` directory in build directory
4. User initializes `uplink-c` and then tries to build again without cleaning.
5. `uplink-c` gets nested in a second level deeper, causing build issues.

uplink-sys(fix): Make build copying more resilient

---

uplink/src/docs/design.rs
uplink/src/helpers.rs

Fix some doc comments lines that were wrongly indented and they were caught by the linter, probably because a new version was able to detect them.

uplink(fix): Fix indentation in doc comments

---

uplink/src/edge/credentials.rs

Previously, `from_ffi_credentials_result()` would free the underlying memory of the strings stored in `Gateway` (the FFI `EdgeCredentialsResult`) upon success, resulting in a use-after-free error for anyone trying to access those strings.
Unfortunately, this will be a breaking change.

uplink(fix): Fix use-after-free bug in `edge::Gateway`

---

uplink-sys/Cargo.toml
uplink/Cargo.toml

Release a new version of each crate to include some merged fixes.
The uplink version includes a fix of a used after free bug. This fix required have breaking changes, unfortunately.
They are published.

uplink-sys,uplink(release): Release new versions

---

uplink-sys/build.rs

To get the target build operating system, `CARGO_CFG_TARGET_OS` should be read instead of `cfg(target_os = "macos")`. The latter detects the host OS that is building the `build.rs` script, not the target OS.

uplink-sys(build): Fix build script for macOS

---

uplink/src/metadata.rs

`char` in C maps to different types in x86 vs. ARM (`i8` vs `u8`). This may affect other architectures as well.
Use `c_char` for FFI instead to avoid compile errors on different architectures.

uplink(fix): Use `c_char` for `char` FFI

---

uplink/src/edge/config.rs

There were 2 bugs in the `register_gateway_access()` code:
1. Most prominently, the function was constructing and passing a dangling pointer to a temporary `EdgeRegisterAccessOptions` to the FFI. In fact, that variable doesn't even live to the point that the FFI is made. While this occurs on the stack and may not always be overwritten, the compiler and program is free to reclaim and reuse that stack space for other things -- it's technically UB. This code is somewhat lucky that this doesn't occur very often because the struct is very small, on the stack, and a boolean.
2. The function was also casting the `*const EdgeRegisterAccessOptions` pointer as mutable in the unsafe block, which violates Rust's aliasing guarantees and can potentially lead to undefined behavior.
cc @ifraixedes - this …

uplink: Fix passing dangling stack pointer

---

Cargo.toml

Enable the resolver version 2 at the workspace level, otherwise, version 1 is used, besides showing a warning about it.

all(build): Enable the resolver v2

---

uplink/Cargo.toml

Release a new uplink crate version that uses the last published uplink-sys version (v0.8.0).
This commit also bumps the uplink crate dependencies.
On hold until #94 is merged.

uplink(release): Release new version (v0.11.0)
